  name: ifilter_mobile_application
  description: iFILTER mobile application is part of the iFILTER Solution for fresh water management

  publish_to: none
  version: 1.0.0+1
  environment:
    sdk: ">=2.19.6 <3.0.0"

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.2
    google_fonts: ^4.0.4
    fl_chart: ^0.35.0
    percent_indicator: ^3.0.1
    intl: ^0.17.0
    carousel_slider: ^4.0.0
    firebase_core: ^2.12.0
    firebase_auth: ^4.6.1
    cloud_firestore: ^4.8.0
    firebase_database: ^10.2.2






  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true
    assets:
      - assets/images/welcome_image/welcome_image.jpg
      - assets/images/login_image/login_image.png
      - assets/images/forget_password/forget_password.png
      - assets/images/profile_image/profile_image.png
      - assets/images/drinking_safety/drinking_safety.png
      - assets/images/system_status/online_system.png
      - assets/images/system_status/offline_system.png
      - assets/images/system_status/system_maintenance.png
      - assets/images/health_check/health_check_image.png
      - assets/images/iFilter_Description/iFilter_cabinet1.jpg
      - assets/images/iFilter_Description/iFilter_cabinet2.png
      - assets/images/iFilter_Description/iFilter_cabinet3.jpg
      - assets/images/iFilter_Description/iFilter_cabinet4.png






