// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEx1GmDIZdA38LasBXXTANLWYwQv3U4Z8',
    appId: '1:178505688610:web:1ccbd288e6c159ef790c7b',
    messagingSenderId: '178505688610',
    projectId: 'ifilter-33bac',
    authDomain: 'ifilter-33bac.firebaseapp.com',
    storageBucket: 'ifilter-33bac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupba-tgSZddXQ0TXEV-PG5oFtbfnXOmI',
    appId: '1:178505688610:android:8ee3b5455e74acf7790c7b',
    messagingSenderId: '178505688610',
    projectId: 'ifilter-33bac',
    storageBucket: 'ifilter-33bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF354hUpqf7IxQS3umpKjYWLBDZttbDlQ',
    appId: '1:178505688610:ios:cfe3ecfc24366c55790c7b',
    messagingSenderId: '178505688610',
    projectId: 'ifilter-33bac',
    storageBucket: 'ifilter-33bac.appspot.com',
    iosClientId: '178505688610-k0ec42f75trq9bmcvju8ils8lch1sa9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifilterMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF354hUpqf7IxQS3umpKjYWLBDZttbDlQ',
    appId: '1:178505688610:ios:cfe3ecfc24366c55790c7b',
    messagingSenderId: '178505688610',
    projectId: 'ifilter-33bac',
    storageBucket: 'ifilter-33bac.appspot.com',
    iosClientId: '178505688610-k0ec42f75trq9bmcvju8ils8lch1sa9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifilterMobileApplication',
  );
}
